import type { MetadataRoute } from 'next';

/**
 * Only the two routes that stand on their own.
 *
 * Asset pages are deliberately absent. There are sixty-one of them today and the set
 * changes as the engine's coverage does, so a sitemap listing them would either be
 * generated by calling the API on every request — spending a rate-limit budget on
 * crawlers — or be a list that goes stale. The monitored set links to all of them.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? 'http://localhost:5173';

  return [
    { url: siteUrl, changeFrequency: 'hourly', priority: 1 },
    { url: `${siteUrl}/methodology`, changeFrequency: 'weekly', priority: 0.8 },
  ];
}
